# Generated by Django 3.1.1 on 2020-09-22 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=40, unique=True)),
                ('votes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=50, unique=True)),
                ('votes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='main.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=60, unique=True)),
                ('votes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemForB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=400)),
                ('votes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemForA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=400)),
                ('votes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='LinkForB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=400)),
                ('votes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='LinkForA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=400)),
                ('votes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=400)),
                ('votes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.keyword')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.Tag'),
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.keyword')),
            ],
        ),
        migrations.AddConstraint(
            model_name='problemforb',
            constraint=models.UniqueConstraint(fields=('keyword_id', 'url'), name='unique_pforbs'),
        ),
        migrations.AddConstraint(
            model_name='problemfora',
            constraint=models.UniqueConstraint(fields=('keyword_id', 'url'), name='unique_pforas'),
        ),
        migrations.AddConstraint(
            model_name='linkforb',
            constraint=models.UniqueConstraint(fields=('keyword_id', 'url'), name='unique_lforbs'),
        ),
        migrations.AddConstraint(
            model_name='linkfora',
            constraint=models.UniqueConstraint(fields=('keyword_id', 'url'), name='unique_lforas'),
        ),
        migrations.AddConstraint(
            model_name='library',
            constraint=models.UniqueConstraint(fields=('keyword_id', 'url'), name='unique_libraries'),
        ),
        migrations.AddConstraint(
            model_name='explanation',
            constraint=models.UniqueConstraint(fields=('keyword_id', 'text'), name='unique_expls'),
        ),
    ]
