# Generated by Django 3.1.1 on 2020-09-12 06:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkForA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=400)),
                ('votes', models.IntegerField(default=0)),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.keyword')),
            ],
        ),
    ]
