# Generated by Django 3.1.1 on 2020-09-12 11:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_linkfora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=40, unique=True)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemForA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=400)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemForB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=400)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=60, unique=True)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='text',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='explanation',
            constraint=models.UniqueConstraint(fields=('keyword_id', 'text'), name='unique_expls'),
        ),
        migrations.AddConstraint(
            model_name='linkfora',
            constraint=models.UniqueConstraint(fields=('keyword_id', 'url'), name='unique_lforas'),
        ),
        migrations.AddConstraint(
            model_name='linkforb',
            constraint=models.UniqueConstraint(fields=('keyword_id', 'url'), name='unique_lforbs'),
        ),
        migrations.AddField(
            model_name='problemforb',
            name='keyword_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.keyword'),
        ),
        migrations.AddField(
            model_name='problemfora',
            name='keyword_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.keyword'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='categories',
            field=models.ManyToManyField(to='main.Category'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
        migrations.AddConstraint(
            model_name='problemforb',
            constraint=models.UniqueConstraint(fields=('keyword_id', 'url'), name='unique_pforbs'),
        ),
        migrations.AddConstraint(
            model_name='problemfora',
            constraint=models.UniqueConstraint(fields=('keyword_id', 'url'), name='unique_pforas'),
        ),
    ]
