# Generated by Django 3.1.1 on 2020-09-13 00:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200912_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanation',
            name='text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='linkfora',
            name='text',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='linkforb',
            name='text',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=400)),
                ('votes', models.IntegerField(default=0)),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.keyword')),
            ],
        ),
        migrations.AddConstraint(
            model_name='library',
            constraint=models.UniqueConstraint(fields=('keyword_id', 'url'), name='unique_libraries'),
        ),
    ]
